# Generated by Django 5.1.7 on 2025-05-22 13:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cash Invoice',
                'verbose_name_plural': 'Cash Invoices',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OfficialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField()),
                ('received_from', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.TextField()),
                ('model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ghc', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Official Receipt',
                'verbose_name_plural': 'Official Receipts',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.cashinvoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
