# Generated by Django 5.1.7 on 2025-06-12 14:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cashinvoice_subtotal_amount_cashinvoice_vat_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinvoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount before VAT', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashinvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated VAT amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cashinvoice',
            name='vat_applicable',
            field=models.BooleanField(default=False, help_text='Whether VAT is applied to this invoice'),
        ),
        migrations.AlterField(
            model_name='cashinvoice',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT percentage (e.g., 15.00 for 15%)', max_digits=5),
        ),
    ]
