# Generated by Django 5.2.8 on 2025-11-28 10:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cashinvoice_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinvoice',
            name='nontax_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total of non-taxable items', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='True for regular products, False for non-tax items like transport'),
        ),
    ]
