# Generated by Django 4.2.17 on 2026-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_cashinvoice_nontax_total_invoiceproduct_is_taxable"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashinvoice",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("FINAL", "Final/Published")],
                default="FINAL",
                max_length=20,
            ),
        ),
    ]
